// src/lib/components/edit-modal.svelte
<script lang="ts">
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import {Code2, Copy} from '@lucide/svelte/icons';
    import {Button} from '$lib/components/ui/button/index'
    import Badge from "$lib/components/ui/badge/badge.svelte";


    let {fileContent,
    selectedFile,
    updateFileContent,handleCopy, 
    isCopied,
    isCodeDialogOpen=$bindable(false)} = $props()

</script>

<Dialog.Root bind:open={isCodeDialogOpen}>
    <Dialog.Content class="w-[80vw] h-[90vh] flex flex-col">
        <Dialog.Header>
            <Dialog.Title class="flex items-center gap-2">
                <Code2 class="h-5 w-5" />
                {selectedFile?.name || 'File Content'}
            </Dialog.Title>
        </Dialog.Header>
        
        <div class="flex-1 flex flex-col min-h-0">
            <div class="flex justify-between items-center mb-3">
                <Badge variant="secondary">
                    {selectedFile?.path}
                </Badge>
                <Button 
                    variant="outline" 
                    size="sm" 
                    onclick={()=>handleCopy(fileContent)}

                >{#if !isCopied}
                    <Copy class="h-4 w-4 mr-2" />
                    Copy
                {:else}
                <Copy class="h-4 w-4 mr-2 text-green-700" />
                <span class="text-green-700">
                    Copied
                </span>
                {/if}</Button>
            </div>
            
            <div class="flex-1 min-h-0 border rounded-md bg-muted/50 ">
                <textarea  bind:value={fileContent} class="p-4 text-sm overflow-auto h-full w-full whitespace-pre-wrap font-mono resize-none">
                {fileContent}
                </textarea>
            </div>
        </div>
        
        <div class="flex justify-end pt-4">
            <Button variant="outline" onclick={() => updateFileContent(fileContent)}>
                Save
            </Button>
        </div>
    </Dialog.Content>
</Dialog.Root>

// src/components/EditModal.tsx
import { CopyIcon } from '../icons';

const EditModal = ({ isOpen, onClose, content, fileName, onSave, onCopy, isCopied, onEdit }) => {
	if (!isOpen) return null;
	return (
		<div
			className="fixed z-10 inset-0 bg-black/60 backdrop-blur-sm transition-opacity flex flex-col items-center justify-center motion-preset-expand"
			onClick={onClose}
		>
			<div
				onClick={(e) => e.stopPropagation()}
				className="w-2/3 h-2/3 flex flex-col rounded-xl border border-gray-600"
			>
				<div className="h-14 bg-[#121212] items-center flex justify-between rounded-t-xl px-4">
					<h2 className="text-sm text-white/60 leading-none">{fileName}</h2>
					<button className="text-white/60 text-lg hover:text-white" onClick={onClose}>
						✕
					</button>
				</div>

				<div className="flex-grow bg-[#282c34] p-4 overflow-auto rounded-md">
					<textarea
						onChange={(e) => onEdit(e.target.value)}
						value={content}
						className="w-full h-full resize-none bg-transparent text-sm font-mono text-white/80 focus:outline-none"
					/>
				</div>

				<div className="h-14 bg-[#121212] flex items-center justify-between px-4 rounded-b-xl">
					<button
						className={`text-white/70 hover:text-white transition-colors flex items-center gap-1 ${
							isCopied ? 'text-green-500' : ''
						}`}
						onClick={() => onCopy(content)}
						title="Copy content"
					>
						{isCopied ? (
							<span className="text-xs text-green-500">Copied!</span>
						) : (
							<>
								<CopyIcon />
								<span className="text-xs">Copy</span>
							</>
						)}
					</button>
					<button
						className="text-black text-sm rounded-md py-2 px-4 bg-white hover:bg-gray-200 transition-colors"
						onClick={() => onSave({ editText: content })}
					>
						Saved
					</button>
				</div>
			</div>
		</div>
	);
};

export default EditModal;
